// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnwevtyrfxylyvfktygv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhud2V2dHlyZnh5bHl2Zmt0eWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2ODUxMTIsImV4cCI6MjA3MzI2MTExMn0.aGy01tyBYvBoia64UAfb7txs71LMjjkEU8N1Te5Hs3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});